Repository CS130-W20/team-A7, pull requests merged in 2020-02, with the labels that each got.

#24 Added About and Login to Navbar
  client/package-lock.json
  client/package.json
  client/src/components/NavBar/NavBar.js
Labels: Frontend

#25 changed color of text - thanks kevin we needed you on this one
  client/src/components/NavBar/NavBar.js
Labels: Frontend, bug, good first issue

#26 quiz starting component
  client/src/components/Quiz/Quiz.js
Labels: Frontend

#29 added linking
  client/package-lock.json
  client/package.json
  client/src/components/About/index.js
  client/src/components/App/App.js
  client/src/components/Landing/index.js
  client/src/components/NavBar/NavBar.js
  client/src/components/Navigation/index.js
  client/src/components/Quiz/Quiz.js
  client/src/components/Quiz/index.js
  client/src/constants/routes.js
Labels: Frontend

#37 Added items to quiz page
  client/package-lock.json
  client/package.json
  client/src/components/Quiz/index.js
Labels: Frontend, Trip Creation

#41 Kyles changes
  client/src/components/App/App.js
  client/src/components/Landing/Landing.js
  client/src/components/NavBar/NavBar.js
  client/src/components/SignUp/index.js
  client/src/constants/routes.js
  client/src/index.css
Labels: Frontend

#45 added misc stuff and forgot password screen
  client/src/components/App/App.js
  client/src/components/NavBar/NavBar.js
  client/src/components/Navigation/index.js
  client/src/components/PasswordChange/index.js
  client/src/components/SignUp/index.js
Labels: Frontend

#59 added link
  client/src/components/App/README.md
Labels: good first issue
